# Generated by Django 2.2.4 on 2019-12-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20191217_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvote',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=20.0, max_digits=6, null=True),
        ),
    ]
