# Generated by Django 2.2.4 on 2019-12-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20191221_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='price',
        ),
        migrations.AddField(
            model_name='ticket',
            name='feature_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=19.99, max_digits=6, null=True),
        ),
    ]
