# Generated by Django 2.2.4 on 2019-12-21 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20191221_0141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='feature_price',
            new_name='upvote_price',
        ),
    ]
