# Generated by Django 2.2.4 on 2019-12-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20191221_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='earned',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
