# Generated by Django 2.2.4 on 2019-09-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='priority',
            field=models.CharField(default='LOW', max_length=8),
        ),
    ]
